apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: oriapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oriapp
  template:
    metadata:
      labels:
        app: oriapp
    spec:
      containers:
      - name: oriapp
        image: origez12/project-app:oriapp
        ports:
        - containerPort: 80